#!/bin/bash

rm roster.js
echo "/* THIS FILE IS AUTOGENERATED BY generate_roster.sh IF SOMETHING LOOKS WRONG HERE, CHECK YOUR SOURCE .tsv FILE RATHER THAN MODIFYING THIS FILE, CHANGES WILL NOT PERSIST. */" >> roster.js
echo "const roster = [" >> roster.js

while IFS=$'\t' read -r first_name last_name year major position hometown high_school
do
  echo $high_school
  hs_length=${#high_school}-1
  hs_no_newline=${high_school:0:${hs_length}}
  echo "{" >> roster.js
  echo firstName: \"$first_name\", >> roster.js
  echo lastName: \"$last_name\", >> roster.js
  echo year: \"$year\", >> roster.js
  echo major: \"$major\", >> roster.js
  echo position: \"$position\", >> roster.js
  echo hometown: \"$hometown\", >> roster.js
  echo highSchool: \"$hs_no_newline\", >> roster.js

  last_name_no_space=$(sed "s/ //g" <<< $last_name)
  first_name_replaced=$(sed "s/'//g" <<< $first_name)
  roster_path=Media/roster_photos/$first_name_replaced$last_name_no_space.jpg
  if test -f $roster_path;
  then
    echo hasRosterPic: true >> roster.js
  else
    echo hasRosterPic: false >> roster.js
  fi
  echo "}," >> roster.js
done < <(tail -n +2 roster.tsv)
echo "];" >> roster.js
