/* THIS FILE IS AUTOGENERATED BY generate_roster.sh IF SOMETHING LOOKS WRONG HERE, CHECK YOUR SOURCE .tsv FILE RATHER THAN MODIFYING THIS FILE, CHANGES WILL NOT PERSIST. */
const roster = [
{
firstName: "Cameron",
lastName: "Bernstein",
year: "Sr",
major: "Statistics",
position: "Webmaster, Secretary",
hometown: "Long Grove, IL",
highSchool: "Adlai E Stevenson High School",
hasRosterPic: true
},
{
firstName: "Ni'Gere",
lastName: "Epps",
year: "Jr",
major: "Computer Science",
position: "Social Chair",
hometown: "Harvey, IL",
highSchool: "Oak Forest High School",
hasRosterPic: true
},
{
firstName: "Samantha",
lastName: "Stagg",
year: "Jr",
major: "Computational and Applied Mathematics",
position: "Co-Captain",
hometown: "Tampa, FL",
highSchool: "Academy of the Holy Names",
hasRosterPic: true
},
{
firstName: "Poppy",
lastName: "Perez Reyes",
year: "Jr",
major: "Comparative Human Development",
position: "None",
hometown: "New York, NY",
highSchool: "The Nightingale-Bamford School",
hasRosterPic: true
},
{
firstName: "Zipporah",
lastName: "Klain",
year: "Jr",
major: "Computer Science, Sociology",
position: "Treasurer",
hometown: "Washington, DC",
highSchool: "James Madison High School",
hasRosterPic: true
},
{
firstName: "Omar",
lastName: "Almakki",
year: "Jr",
major: "Theater and Performance Studies, Biological Sciences",
position: "Co-Captain",
hometown: "West Lafayette, IN",
highSchool: "William Henry Harrison High School",
hasRosterPic: true
},
{
firstName: "Brooke",
lastName: "Werdlow",
year: "Jr",
major: "Cinema Media Studies",
position: "None",
hometown: "Detroit, MI",
highSchool: "Detroit Country Day",
hasRosterPic: false
},
{
firstName: "Sophia",
lastName: "Abanov",
year: "Jr",
major: "Mathematics with Specialization in Economics",
position: "Choreographer",
hometown: "East Setauket, NY",
highSchool: "Ward Melville High School",
hasRosterPic: true
},
{
firstName: "Heather",
lastName: "Weller",
year: "Jr",
major: "Public Policy",
position: "None",
hometown: "New York Mills, MN",
highSchool: "New York Mills High School",
hasRosterPic: true
},
{
firstName: "Kara",
lastName: "Hairston",
year: "Sr",
major: "Psychology",
position: "None",
hometown: "Indianapolis, IN",
highSchool: "Lawrence Central High School",
hasRosterPic: true
},
{
firstName: "Eden",
lastName: "Grosz",
year: "Fr",
major: "Psychology",
position: "None",
hometown: "Miami Beach, FL",
highSchool: "Hebrew Academy Miami",
hasRosterPic: true
},
{
firstName: "Jillyn",
lastName: "Turunen",
year: "Fr",
major: "Neuroscience, Linguistics",
position: "None",
hometown: "Glendora, CA",
highSchool: "Glendora High School",
hasRosterPic: true
},
{
firstName: "Tasnim",
lastName: "Khan",
year: "Fr",
major: "Physics",
position: "None",
hometown: "New York, New York",
highSchool: "Stuyvesant High School",
hasRosterPic: false
},
{
firstName: "Kiki",
lastName: "Downey",
year: "Grad",
major: "English, Marketing",
position: "None",
hometown: "Boston, MA",
highSchool: "Magdalen College, University of Oxford",
hasRosterPic: true
},
{
firstName: "Sophia",
lastName: "Pegues",
year: "Fr",
major: "Undeclared",
position: "None",
hometown: "Greenbrier, AK",
highSchool: "Quitman High School",
hasRosterPic: true
},
];
